### ISSUE TITLE
Get a compiler error when using an example 

### ISSUE THREAD

**Issue by sweshn** [khoih-prog/RP2040_RTC#5]
### Describe the bug
Get a compiler error when using an example 

### Steps to Reproduce

load  sketch: RP2040_RTC_Time.ino  compile

### Expected behavior

no error

### Actual behavior

compiler error

### Screenshots
ERRORTEXT:   ::clock' has not been declared
   using ::clock;

### Information

Please ensure to specify the following:

* Arduino IDE version . 2.0.0.rc2
* Arduino-mbed RP2040 v2.6.1
* `NANO_RP2040_CONNECT

  * Operating system Windows11
  * Network configuration
  
### Additional context

I have just started to use RP2040 so it can be a "user" error

**Comment by khoih-prog** [comment]
Hi @sweshn 

Thanks for your interest in the library.

**Be confident from now on** that you've done nothing wrong. The real issue is that I forgot to update this [**RP2040_RTC** Library](https://github.com/khoih-prog/RP2040_RTC) after breaking change in [**Timezone_Generic** releases v1.8.0](https://github.com/khoih-prog/Timezone_Generic/releases/tag/v1.8.0), on which this library depends.

I've just updated and published the [**Timezone_Generic** releases v1.9.0](Timezone_Generic/releases/tag/v1.9.0) to make compatible to old code.

So now you just update to [**Timezone_Generic** releases v1.9.0](Timezone_Generic/releases/tag/v1.9.0) and you will be OK.

Regards,

**Comment by sweshn** [comment]
Hi
Thanks for fast response !! 
But sorry to say i dosen´t work. Have installed on a "new" laptop IDE 1.8.19,, rp2040_rtc v 1.08 ans Timezone 1.9.0 mbed os rp2040 2.6.1.
Still the same error :  using ::gmtime;
                                            ^~~~~~

//Staffan

**Comment by khoih-prog** [comment]
Hi,

I'm sorry to confirm that you have done something wrong with the installation, such as missing library, files, etc.

I tested here and everything is OK so far with IDE v1.8.19, library v1.0.8 and `mbed_nano` / `mbed_rp2040` core v2.6.1

![Selection_091](https://user-images.githubusercontent.com/57012152/150610257-0047d0de-8c96-4f0d-9a07-943e6be92f1e.png)

![Selection_090](https://user-images.githubusercontent.com/57012152/150610267-240efeb7-8670-4356-a77f-695474491209.png)


**Don't be discouraged**. Try the simplest steps, and compile using the core examples to verify before going any further.

After this experiment, I'm sure you'll learn a lot of things. 

If still having issue, I suggest you post in [**Arduino Forum**](https://forum.arduino.cc/c/hardware/nano-family/nano-rp2040-connect/165) so that other people with more experience in dealing with installation issues can help you out as I don't have time to deal with those installation issues.


Good Luck,

**Comment by sweshn** [comment]
Hi

After unistall and install several times it suddenly works !!!

Thanks!

//staffan

Skickades från E-post för Windows

Från: Khoi Hoang
Skickat: den 21 januari 2022 23:56
Till: khoih-prog/RP2040_RTC
Kopia: sweshn; Mention
Ämne: Re: [khoih-prog/RP2040_RTC] Get a compiler error when using anexample (Issue #5)

Hi,
I'm sorry to confirm that you have done something wrong with the installation, such as missing library, files, etc.
I tested here and everything is OK so far with IDE v1.8.19, library v1.0.8 and mbed_nano / mbed_rp2040 core v2.6.1


Don't be discouraged. Try the simplest steps, and compile using the core examples to verify before going any further.
After this experiment, I'm sure you'll learn a lot of things.
If still having issue, I suggest you post in Arduino Forum so that other people with more experience in dealing with installation issues can help you out as I don't have time to deal with those installation issues.
Good Luck,
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
